@startuml

skinparam linetype ortho
skinparam actorStyle awesome

skinparam actor<<Atkeur>> {
  BackgroundColor #575756
  BorderColor Black
}

skinparam rectangle<<Atkeur>> {
  MinimumWidth 10000
  BackgroundColor #decabd
  ' BorderColor black
  ' ArrowColor black
  ' ActorBorderColor black
  ' ActorFontName Courier
}

skinparam usecase {
  BackgroundColor #b8d5e8
  ' BorderColor black
  ' ArrowColor black
  ' ActorBorderColor black
  ' ActorFontName Courier
}


left to right direction
actor Patient <<Atkeur>> as patient
actor GDA <<Atkeur>> as gda
rectangle "e-Medikation"<<Atkeur>> as reg_emed
rectangle " e-Impfpass "<<Atkeur>> as reg_impf
rectangle "    etc.    "<<Atkeur>> as reg_etc
rectangle "Bestehende Register"<<Atkeur>> as reg_bestReg

package "Austrian Patient Summary" {
  usecase "UC1 aktualisieren/erstellen" as UC1
  usecase "UC2 lesen" as UC2
}

patient -- UC2
gda -- UC2
gda -- UC1

UC1 -- reg_bestReg
reg_bestReg <|-down- reg_emed
reg_bestReg <|-down- reg_impf
reg_bestReg <|-down- reg_etc


@enduml